repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.5
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix]
      # Run the formatter
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
      - id: check-toml
      - id: check-json
      - id: pretty-format-json
        args: [--autofix]
      - id: detect-private-key
      - id: no-commit-to-branch
        args: [--branch, main, --branch, master]
      - id: check-case-conflict
      - id: check-symlinks
      - id: destroyed-symlinks

  # Security checks
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        exclude: |
          (?x)^(
            .*\.lock|
            \.secrets\.baseline
          )$

  # Prevent committing sensitive files
  - repo: local
    hooks:
      - id: forbid-sensitive-files
        name: Forbid committing sensitive files
        entry: Sensitive files detected
        language: fail
        files: |
          (?x)^(
            .*\.(pem|key|p12|pfx|cert|crt|cer|der|ca|keystore|jks|truststore)|
            (\.env$|\.env\.[^e].*|\.env\.e[^x].*|\.env\.ex[^a].*|\.env\.exa[^m].*|\.env\.exam[^p].*|\.env\.examp[^l].*|\.env\.exampl[^e].*)|
            secret|secrets|credentials|password|passwd|
            id_rsa|id_dsa|id_ecdsa|id_ed25519|
            .*_rsa|.*_dsa|.*_ecdsa|.*_ed25519|
            aws_access_key_id|aws_secret_access_key|
            google.*\.json|service.*account.*\.json|
            .*\.kdbx|.*\.keychain|.*\.kwallet|
            \.aws/credentials|
            \.ssh/.*|
            \.gnupg/.*|
            \.docker/config\.json|
            kubeconfig|\.kube/config
          )$

      - id: check-env-files
        name: Check for .env files
        entry: Environment files must not be committed
        language: fail
        files: '\.env$|\.env\.[^e].*|\.env\.e[^x].*|\.env\.ex[^a].*|\.env\.exa[^m].*|\.env\.exam[^p].*|\.env\.examp[^l].*|\.env\.exampl[^e].*'

      - id: check-certificates
        name: Check for certificate files
        entry: Certificate files must not be committed
        language: fail
        files: '\.(pem|crt|cer|ca|key|p12|pfx|jks)$'

  # Additional security scanning
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.21.2
    hooks:
      - id: gitleaks
